Isolate the Node 10-only parts in their own directory
Jomik/screeps-server pull request #149
Opened 2024-09-30 15:20 UTC by tiennou

This allows enabling TypeScript from the outer side, so that the server scripts can be checked by it without requiring the inner side to care.

2024-09-30 15:25 UTC, Jomik requested changes
I'll check this out on my computer when I'm able 👍

2024-09-30 15:25 UTC, Jomik commented on server/screeps-start.js
> +  // @ts-expect-error We can't load that from the outer non-Node 10 side
I'd prefer a `@ts-ignore` 🤔

2024-09-30 15:25 UTC, Jomik commented on server/package.json
> +  "repository": "git@github.com-private:Jomik/screeps-server.git",
Just noticed this -private is "wrong" 😁

2024-09-30 15:25 UTC, Jomik commented on tsconfig.json
> +  "compilerOptions": {
Can we remove the comments for unused options?

2024-09-30 15:44 UTC, tiennou commented
Okay, another update. Fixed all the review comments. I don't think I can fix CI, it's running that against your workflows, and thus hasn't caught onto the Dockerfile having moved to `server`. But the script files are now TS-strict-checked, and you can pretty much edit them using whatever version of Node you are running. Actually, I can .nvmrc pin it inside that folder now, let me do that…

2024-10-05 08:05 UTC, Jomik requested changes
Let's make the `js` files `cjs` files to remove that annoying "can be converted to ESModule" warning.

2024-10-05 08:05 UTC, Jomik commented on package.json
> +    "@types/node": "^10.17.60"
Let's add `typescript` as a dependency.

2024-10-05 08:05 UTC, Jomik commented on server/.nvmrc
Probably don't really need this - I doubt anyone would try to install the server locally.

2024-10-05 08:05 UTC, Jomik commented on server/package.json
> +    "cli": "docker compose exec screeps cli"
```suggestion
```
Let's not have this - we don't use this package.json for anything other than building the image

2024-10-05 08:05 UTC, Jomik commented on tsconfig.json
> +    "skipLibCheck": true
```suggestion
    "skipLibCheck": true
```

2024-10-07 16:50 UTC, tiennou commented on server/.nvmrc
Oh, it's so that if you cd into that folder, you edit the lock file with the correct NPM version. In case you want to install something else in the Node 10 env. Not that you would be able to, since that attempts to install the server, which is likely to break. So… yeah. It's just a safety measure to make sure the lockfile doesn't get upgraded for some reason.

2024-10-07 16:58 UTC, tiennou commented
Okay, updated. I kept the .nvmrc file in because I think it makes it more obvious than this is a "weird" area. I hope I got the `.js`->`.cjs` rename correct, too. I know I saw that warning a few times, but can't remember what I was doing at the time.

2024-10-07 17:04 UTC, Jomik commented on server/.nvmrc
Yah, awesome. I get the point, but `.nvmrc` depends on you having a version manager installed and also actively switching to that version, unless you set it up to be automatic.
The `engines` field in package.json should take care of it for us though 😄

2024-10-07 17:04 UTC, merged